ARG FROM_REPO=gru.ocir.io/grq1iurfepyg/manageiq
ARG FROM_TAG=latest-quinteros
ARG FROM_IMAGE=${FROM_REPO}/manageiq-webserver-worker:${FROM_TAG}

FROM ${FROM_IMAGE}

LABEL name="manageiq-ui-worker" \
      summary="ManageIQ user interface worker image"
