ARG FROM_REPO=gru.ocir.io/grq1iurfepyg/manageiq
ARG FROM_TAG=latest-quinteros

FROM ${FROM_REPO}/manageiq-webserver-worker:${FROM_TAG}

LABEL name="manageiq-ui-worker" \
      summary="ManageIQ user interface worker image"
