name: Build Pods
on:
  repository_dispatch:
    types:
    - build
  workflow_dispatch:
jobs:
  build_pods:
    if: github.repository_owner == 'datacosmos-br'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'manageiq-operator/go.mod'
    - name: Build pods containers
      run: bin/build -t latest-radjabov -n

