name: Update Go Dependencies

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  go_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'manageiq-operator/go.mod'
    - name: Update all dependencies
      run: |
        go get -t -u ./...
        go mod tidy
      working-directory: ./manageiq-operator
